name: lint
on:
  # 手動実行できるようにする
  workflow_dispatch:
  pull_request:
    branches: 
      - "**"
  push:
    branches:
      - "**"
jobs:
  stylua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JohnnyMorganz/stylua-action@1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # CLI arguments
          args: --check .
          # Specify `version` to pin a specific version, otherwise action will always use latest version/automatically update
